runtime: python312

entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000

env_variables:
  # Imposta qui le variabili sensibili oppure usa Secret Manager
  ISTA_USERNAME: ""
  ISTA_PASSWORD: ""
  WCD_URL: euaollxerumlvktea79rzq.c0.europe-west3.gcp.weaviate.cloud
  WCD_API_KEY: Q3FPaExkZHhDVkE3QXZMRF9GZVN6ek11RDZ4aUNFdlRab0x0WE42cGR3UWlQaUpsMWV5TGt2RWdTOS9VPV92MjAw
  OPENAI_API_KEY: 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
  WCD_COLLECTION_NAME: Recipe_Vector
